on:
 push:
   branches:
     - main  # Change this to your desired branch
jobs:
 unzip:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Unzip Folder
       run: unzip kfc.zip
     - name: Commit and Push Changes
       run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git add .
         git commit -m "Automatically unzip folder"
         git push
